// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csufqjwtvylpirjsqgia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdWZxand0dnlscGlyanNxZ2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjM5OTYsImV4cCI6MjA2NDczOTk5Nn0.YOUOq9cSpI2Tbf-ELgysC30e2g2WMpTy6mCZ_s8ogcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);